#include <stdlib.h>
#include <iostream>

#include "euler_functions.h"


// Triangle, pentagonal, and hexagonal numbers are generated by the following formulae :
//      Triangle 	: Tn = n(n + 1) / 2 	1, 3, 6, 10, 15, ...
//      Pentagonal 	: Pn = n(3n−1) / 2 	  	1, 5, 12, 22, 35, ...
//      Hexagonal 	: Hn = n(2n−1) 	  	    1, 6, 15, 28, 45, ...
//
// It can be verified that T285 = P165 = H143 = 40755.
//
// Find the next triangle number that is also pentagonal and hexagonal.

int main(int argc, char **argv)
{
#ifdef _WIN64
    for (size_t n = 1;; ++n)
    {
        size_t Hn = n * (2 * n - 1);

        double sqr = 0;

        //Hexagonal already triangle, so this condition can be skipped (by community) 
        if (modf(sqrt(8 * Hn + 1), &sqr))
            continue;

        if (modf(sqrt(24 * Hn + 1), &sqr))
            continue;

        if ((size_t)sqr % 6 != 5)
            continue;

#ifdef _DEBUG
        printf("%Iu\n", Hn);
#endif
        if (Hn > 40755)
        {
            printf("\nResult: %Iu\n", Hn);
            break;
        }
    }
#endif

    return 0;
}
